package example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Mortgage implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Double salary;
   private Double housePrice;
   private java.lang.Double interestRate;

   private boolean approved;

   public Mortgage()
   {
   }

   public java.lang.Double getSalary()
   {
      return this.salary;
   }

   public void setSalary(java.lang.Double salary)
   {
      this.salary = salary;
   }

   public java.lang.Double getInterestRate()
   {
      return this.interestRate;
   }

   public void setInterestRate(java.lang.Double interestRate)
   {
      this.interestRate = interestRate;
   }

   public boolean isApproved()
   {
      return this.approved;
   }

   public void setApproved(boolean approved)
   {
      this.approved = approved;
   }

   public java.lang.Double getHousePrice()
   {
      return this.housePrice;
   }

   public void setHousePrice(java.lang.Double housePrice)
   {
      this.housePrice = housePrice;
   }

   public Mortgage(java.lang.Double salary, java.lang.Double housePrice,
         java.lang.Double interestRate, boolean approved)
   {
      this.salary = salary;
      this.housePrice = housePrice;
      this.interestRate = interestRate;
      this.approved = approved;
   }

}